---
- hosts: localhost
  remote_user: ansible
  #sudo: yes
  become: true
  vars:
    jdk_dir: 8.222.10.1
    jdk_archive: amazon-corretto-8.222.10.1-linux-x64.tar.gz
    jdk_local_dir: jdk1.8.0_222
    download_folder: /opt/jvm
    bin_dir: /usr/bin
    profile_path: /etc/ama_profile.d
    java_name: "{{ download_folder }}/{{ jdk_local_dir }}"
    java_archive: "{{ download_folder }}/{{ jdk_archive }}"
    download_url: https://d3pxv6yz143wms.cloudfront.net/{{jdk_dir}}/{{jdk_archive}}
    java_version: 8
    java_subversion: 222
    java_build_custom: 10.1
    jdk_version_detail_custom: "{{ java_version }}.{{ java_subversion }}.{{ java_build_custom }}"
    #jdk_tarball_hash: 6599a081ce56dda81ee7ac23802d6e67
    jdk_tarball_url: "https://d3pxv6yz143wms.cloudfront.net/{{ jdk_version_detail_custom }}/{{ jdk_archive }}"

  tasks:
  - name: Create Directory structure
    command: mkdir -p {{download_folder}}
    command: mkdir -p {{java_name}}

  - name: Download Java
    get_url: url={{ jdk_tarball_url }}  dest={{ java_archive }} owner=ed group=ed mode=744

  - name: Unpack archive
    action: shell tar -xzvf {{java_archive}} -C {{download_folder}}

  - name: Fix ownership
    file: state=directory path={{java_name}} owner=root group=root recurse=yes
